### ISSUE TITLE
Add word definitions to search.html and index.html using hover textboxes

### ISSUE THREAD

**Issue by hils124** [marklogic/bitemp-explorer#39]
Words with Definitions: Bitemporal, URI, Valid Time, System Time, Temporal Collection, Logical Document and Physical Document (when you hover over the names of each one in the bullet list)

**Comment by dmcassel** [comment]
The list looks good. Will you be doing this for each occurrence of the terms on each page? Will you do anything to visually indicate that a definition is available? I don't see the term "physical document" on either page -- where do you plan to add it?

**Comment by hils124** [comment]
By physical and logical document, we mean the name of each physical and logical document. For example, if someone hovers over addr.19348091384813948.json then a definition of "physical document" will appear. If you hover over addr.json, where addr.json is a link because it's a logical document, then a definition of "logical document" will appear.

**Comment by ghost** [comment]
Also, we aren't sure how exactly we want to visually indicate that a definition is available. Any ideas?

**Comment by dmcassel** [comment]
Visual indication: maybe a different background color, like a darker grey than the surrounding area. I think you don't want anything too dramatic (or distracting), just a way to tell where you can get help without having to point to everything.

**Comment by ghost** [comment]
<img width="453" alt="screen shot 2015-07-20 at 12 04 56 pm" src="https://cloud.githubusercontent.com/assets/6834776/8784562/93ee54c8-2ed7-11e5-970a-bda9f8b376ad.png">

Right now this is what it looks like when you hover over a word. But the highlight only appears when you are actually hovering over the word

**Comment by dmcassel** [comment]
That looks fine for the pop-up; I'm suggesting a non-intrusive background color (highlight) for terms where that will happen. Having a feature is good; having a discoverable feature so people know it's there is better!

**Comment by ghost** [comment]
<img width="1262" alt="screen shot 2015-07-20 at 1 36 43 pm" src="https://cloud.githubusercontent.com/assets/6834776/8786679/6cf96396-2ee4-11e5-8657-3a95f49d23c7.png">

We are having difficulties with highlighting the valid time and system time because it highlights the entire line...do you know a good way to go about fixing this? Thanks

**Comment by ghost** [comment]
<img width="1264" alt="screen shot 2015-07-20 at 1 42 01 pm" src="https://cloud.githubusercontent.com/assets/6834776/8786789/2182cc4e-2ee5-11e5-86f2-614c2ae06875.png">

Oh and we changed the highlight color like you asked

**Comment by dmcassel** [comment]
Get more specific with your CSS selector, or even easier, create a class for those terms you want highlighted, then add that class to the text that should get highlighted. If the text appears inside of a bigger string, use a span: &lt;h1&gt;MarkLogic &lt;span class="definition"&gt;Bitemporal&lt;/span&gt; Search Page&lt;/h1&gt;

**Comment by ghost** [comment]
<img width="908" alt="screen shot 2015-07-20 at 1 46 40 pm" src="https://cloud.githubusercontent.com/assets/6834776/8786907/d606d46c-2ee5-11e5-97d5-01a6d0e0aae8.png">
<img width="641" alt="screen shot 2015-07-20 at 1 47 04 pm" src="https://cloud.githubusercontent.com/assets/6834776/8786911/d87deeb0-2ee5-11e5-92a2-2cac05c14854.png">

So we did make a class called 'definitions' that does just that, but when we make the Valid and System times' tag have that class, it makes the highlighting funky. I think its because it is a <ul> tag and we aren't sure how to add a span tag or something since we are in javascript. The first image shows our class and the second one shows the valid/system time code

**Comment by dmcassel** [comment]
Looks reasonable from what I see. I'd need a better understanding of "funky".

**Comment by hils124** [comment]
Haha by "funky" I mean like the picture above where it highlights the whole valid time line and same with the system time line. That code is the code for the picture we sent above

**Comment by dmcassel** [comment]
See my [highlighting branch](https://github.com/dmcassel/bitemp-explorer/tree/highlighting). Look in search.html and search.js. I restructured a bit, including adding some nesting for the date/times, then set display:inline-block on the label.
